# Generated by Django 4.0.3 on 2022-06-12 11:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import valdata.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bbox',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('min_margin_ratio', models.FloatField(blank=True, null=True)),
                ('box_center_x', models.IntegerField(blank=True, null=True)),
                ('box_center_y', models.IntegerField(blank=True, null=True)),
                ('box_width', models.IntegerField(blank=True, null=True)),
                ('box_height', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('original_image', models.ImageField(blank=True, null=True, upload_to=valdata.models.data_directory_path)),
                ('segmentation_image', models.ImageField(blank=True, null=True, upload_to=valdata.models.data_directory_path)),
                ('margin_ratio', models.FloatField(blank=True, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Margin',
            fields=[
                ('margin_num', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('margin_x', models.IntegerField(blank=True, null=True)),
                ('real_margin', models.FloatField(blank=True, null=True)),
                ('margin_ratio', models.FloatField(blank=True, null=True)),
                ('margin_width', models.FloatField(blank=True, null=True)),
                ('cut_off', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('bbox', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bboxs', to='valdata.bbox')),
            ],
        ),
        migrations.AddField(
            model_name='bbox',
            name='data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='valdata.data'),
        ),
    ]
