# Generated by Django 4.0.3 on 2022-03-29 10:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anotations',
            fields=[
                ('anotation_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('cut_off', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='Bbox',
            fields=[
                ('box_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('min_margn_ratio', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('box_min_x', models.IntegerField()),
                ('box_min_y', models.IntegerField()),
                ('box_width', models.IntegerField()),
                ('box_height', models.IntegerField()),
                ('anotations', models.ForeignKey(db_column='anotations', on_delete=django.db.models.deletion.CASCADE, to='valdata.anotations')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('img_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Margin',
            fields=[
                ('margin_num', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('real_margin', models.IntegerField()),
                ('margin_ratio', models.IntegerField()),
                ('Bbox', models.ForeignKey(db_column='bbox', on_delete=django.db.models.deletion.CASCADE, to='valdata.bbox')),
            ],
        ),
        migrations.CreateModel(
            name='Box_segmentation',
            fields=[
                ('segmentation_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('segmentation_point', models.IntegerField()),
                ('Bbox', models.ForeignKey(db_column='bbox', on_delete=django.db.models.deletion.CASCADE, to='valdata.bbox')),
            ],
        ),
        migrations.AddField(
            model_name='anotations',
            name='data',
            field=models.ForeignKey(db_column='data', on_delete=django.db.models.deletion.CASCADE, to='valdata.data'),
        ),
    ]
