# Generated by Django 4.0.3 on 2022-04-27 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valdata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bbox',
            old_name='min_margn_ratio',
            new_name='min_margin_ratio',
        ),
    ]
