# Generated by Django 4.0.3 on 2022-04-12 12:49

import django.core.validators
from django.db import migrations, models
import valdata.models


class Migration(migrations.Migration):

    dependencies = [
        ('valdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box_segmentation',
            name='Bbox',
        ),
        migrations.RenameField(
            model_name='bbox',
            old_name='box_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='img_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='bbox',
            name='anotations',
        ),
        migrations.RemoveField(
            model_name='bbox',
            name='box_min_x',
        ),
        migrations.RemoveField(
            model_name='bbox',
            name='box_min_y',
        ),
        migrations.RemoveField(
            model_name='data',
            name='image',
        ),
        migrations.RemoveField(
            model_name='margin',
            name='Bbox',
        ),
        migrations.AddField(
            model_name='bbox',
            name='box_center_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bbox',
            name='box_center_y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bbox',
            name='margin',
            field=models.ManyToManyField(blank=True, related_name='bbox', to='valdata.margin'),
        ),
        migrations.AddField(
            model_name='data',
            name='bbox',
            field=models.ManyToManyField(blank=True, related_name='data', to='valdata.bbox'),
        ),
        migrations.AddField(
            model_name='data',
            name='original_image',
            field=models.ImageField(blank=True, null=True, upload_to=valdata.models.data_directory_path),
        ),
        migrations.AddField(
            model_name='data',
            name='segmentation_image',
            field=models.ImageField(blank=True, null=True, upload_to=valdata.models.data_directory_path),
        ),
        migrations.AddField(
            model_name='margin',
            name='cut_off',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='margin',
            name='margin_width',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='margin',
            name='margin_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bbox',
            name='box_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bbox',
            name='box_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bbox',
            name='min_margn_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='margin',
            name='margin_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='margin',
            name='real_margin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Anotations',
        ),
        migrations.DeleteModel(
            name='Box_segmentation',
        ),
    ]
