# Generated by Django 4.0.3 on 2022-04-12 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valdata', '0002_remove_box_segmentation_bbox_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bbox',
            name='margin',
        ),
        migrations.RemoveField(
            model_name='data',
            name='bbox',
        ),
        migrations.AddField(
            model_name='bbox',
            name='data',
            field=models.ForeignKey(db_column='data', null=True, on_delete=django.db.models.deletion.CASCADE, to='valdata.data'),
        ),
        migrations.AddField(
            model_name='margin',
            name='bbox',
            field=models.ForeignKey(db_column='bbox', null=True, on_delete=django.db.models.deletion.CASCADE, to='valdata.bbox'),
        ),
    ]
