# Generated by Django 3.2.13 on 2022-06-26 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valdata', '0002_rename_margin_num_margin_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='margin',
            name='cut_off',
        ),
    ]
