# Generated by Django 4.0.3 on 2022-04-12 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valdata', '0003_remove_bbox_margin_remove_data_bbox_bbox_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbox',
            name='data',
            field=models.ForeignKey(db_column='data', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data', to='valdata.data'),
        ),
        migrations.AlterField(
            model_name='margin',
            name='bbox',
            field=models.ForeignKey(db_column='bbox', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bbox', to='valdata.bbox'),
        ),
    ]
