# Generated by Django 3.2.13 on 2022-06-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valdata', '0003_remove_margin_cut_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='margin',
            name='margin_y',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
