# Generated by Django 4.0.3 on 2022-04-13 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valdata', '0004_alter_bbox_data_alter_margin_bbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbox',
            name='data',
            field=models.ForeignKey(db_column='data', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='valdata.data'),
        ),
        migrations.AlterField(
            model_name='margin',
            name='bbox',
            field=models.ForeignKey(db_column='bbox', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bboxs', to='valdata.bbox'),
        ),
    ]
