# Generated by Django 3.2.13 on 2022-07-03 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valdata', '0004_margin_margin_y'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bbox',
            old_name='box_center_x',
            new_name='box_x',
        ),
        migrations.RenameField(
            model_name='bbox',
            old_name='box_center_y',
            new_name='box_y',
        ),
    ]
