# Generated by Django 3.2.13 on 2022-08-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valdata', '0007_manuallog'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=10)),
                ('threshold', models.FloatField()),
            ],
        ),
    ]
