# Generated by Django 3.2.13 on 2022-10-09 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valdata', '0009_auto_20221009_2005'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Modelinfo',
            new_name='InferencePath',
        ),
    ]
