# Generated by Django 3.2.13 on 2023-01-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valdata', '0013_auto_20230101_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='pid',
            field=models.IntegerField(default=-1),
        ),
    ]
