# Generated by Django 3.2.13 on 2023-01-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valdata', '0014_state_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
