# Generated by Django 3.2.13 on 2023-01-15 12:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('valdata', '0015_alter_data_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='created_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 15, 12, 58, 57, 293000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='data',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
