# Generated by Django 4.0.3 on 2022-03-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(default='', max_length=100)),
                ('name', models.CharField(max_length=30)),
                ('nickname', models.CharField(default='NickName', max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
